using System;
using System.Collections.Generic;

#nullable disable

namespace API.ModelsDB
{
    public partial class VDprqbBiDev
    {
        public string SortParentAndDeliveryDate { get; set; }
        public string Sub03KeyAccounter { get; set; }
        public string FilterRelevant { get; set; }
        public int? DateDiffPlannedActual { get; set; }
        public int DatabaseId { get; set; }
        public string Sort2 { get; set; }
        public string Sort { get; set; }
        public string OrdernumberParent { get; set; }
        public string ArticleDescription { get; set; }
        public string SeasonTitle { get; set; }
        public string ProductGroup { get; set; }
        public string OrderNumber { get; set; }
        public string CustomerOrderNumber { get; set; }
        public string Customer { get; set; }
        public string Merchandiser { get; set; }
        public string Supplier { get; set; }
        public string Factory { get; set; }
        public DateTime? FactoryDeliveryDate { get; set; }
        public double? QuantityOrderedByClient { get; set; }
        public double? QuantityPlacedAtFactory { get; set; }
        public double? OrderQuantityCartons { get; set; }
        public double? Lot { get; set; }
        public string Crd { get; set; }
        public DateTime? DeliveryDateFrom { get; set; }
        public DateTime? DeliveryDateTo { get; set; }
        public int? DaysToDelivery { get; set; }
        public string TermsOfDelivery { get; set; }
        public string TermsOfPayment { get; set; }
        public DateTime? OrderModified { get; set; }
        public DateTime? Eimodified { get; set; }
        public DateTime? OrderCreationDate { get; set; }
        public DateTime? ShipmentDateOriginal { get; set; }
        public string LastThree { get; set; }
        public double? SeasonSort { get; set; }
        public string ProcurementQb { get; set; }
        public DateTime? StatusDateOverall { get; set; }
        public DateTime? ProductionStart { get; set; }
        public DateTime? StatusPackeddate01 { get; set; }
        public DateTime? StatusPackeddate02 { get; set; }
        public DateTime? StatusPackeddate03 { get; set; }
        public int? ItemsPacked01 { get; set; }
        public int? ItemsPacked02 { get; set; }
        public int? ItemsPacked03 { get; set; }
        public DateTime? StatusKnittingdate01 { get; set; }
        public DateTime? StatusKnittingdate02 { get; set; }
        public DateTime? StatusKnittingdate03 { get; set; }
        public int? Knitting01 { get; set; }
        public int? Knitting02 { get; set; }
        public int? Knitting03 { get; set; }
        public DateTime? StatusCuttingdate01 { get; set; }
        public DateTime? StatusCuttingdate02 { get; set; }
        public DateTime? StatusCuttingdate03 { get; set; }
        public int? Cutting01 { get; set; }
        public int? Cutting02 { get; set; }
        public int? Cutting03 { get; set; }
        public DateTime? StatusSewingdate01 { get; set; }
        public DateTime? StatusSewingdate02 { get; set; }
        public DateTime? StatusSewingdate03 { get; set; }
        public int? Sewing01 { get; set; }
        public int? Sewing02 { get; set; }
        public int? Sewing03 { get; set; }
        public DateTime? StatusWashReceiveddate01 { get; set; }
        public DateTime? StatusWashReceiveddate02 { get; set; }
        public DateTime? StatusWashReceiveddate03 { get; set; }
        public int? WashReceived01 { get; set; }
        public int? WashReceived02 { get; set; }
        public int? WashReceived03 { get; set; }
        public DateTime? StatusAccessoriesDate { get; set; }
        public int? Accessories { get; set; }
        public DateTime? StatusCartonsCompletedDate { get; set; }
        public int? CartonsCompleted { get; set; }
        public DateTime? StatusCartonsShippedDate { get; set; }
        public int? CartonsShipped { get; set; }
        public DateTime? StatusIroningDate { get; set; }
        public int? Ironing { get; set; }
        public DateTime? StatusDailyOutputDate { get; set; }
        public int? DailyOutput { get; set; }
        public DateTime? StatusLinesRunningDate { get; set; }
        public int? LinesRunning { get; set; }
        public DateTime? StatusWashSentDate { get; set; }
        public int? WashSent { get; set; }
        public DateTime? StatusZipperDate { get; set; }
        public int? Zipper { get; set; }
        public DateTime? StatusMotherVesselDate { get; set; }
        public string MotherVessel { get; set; }
        public DateTime? StatusPcsSetDate { get; set; }
        public string PcsSet { get; set; }
        public int? Dprqbid { get; set; }
        public int? OrderId { get; set; }
        public DateTime? ReportAldiDate { get; set; }
        public DateTime? OnSaleDate { get; set; }
        public DateTime? RevisedEtd { get; set; }
        public DateTime? RevisedEta { get; set; }
        public int? StylesCount { get; set; }
        public string KnitWoven { get; set; }
        public string FabricsFrom { get; set; }
        public DateTime? PhotoSampleDueDate { get; set; }
        public DateTime? CdExDate { get; set; }
        public string TestingLab { get; set; }
        public DateTime? OrigSamplePickDate { get; set; }
        public DateTime? NewSamplePickDate { get; set; }
        public string SpshortResult { get; set; }
        public string SpfinalResult { get; set; }
        public string Frilab { get; set; }
        public DateTime? Fri1Date { get; set; }
        public int? Fri1Qty { get; set; }
        public string Fri1Result { get; set; }
        public DateTime? Fri2Date { get; set; }
        public int? Fri2Qty { get; set; }
        public string Fri2Result { get; set; }
        public DateTime? Fri3Date { get; set; }
        public int? Fri3Qty { get; set; }
        public string Fri3Result { get; set; }
        public string ForwarderFreight { get; set; }
        public string ForwarderDelivery { get; set; }
        public DateTime? BlreceivedDate { get; set; }
        public DateTime? StatusDate { get; set; }
        public string Comment { get; set; }
        public string MerchandiserSupplier { get; set; }
        public DateTime? PhotoSampleRevisedDate { get; set; }
        public string ShippingSchedule { get; set; }
        public DateTime? ReSamplePick { get; set; }
        public string Comment2 { get; set; }
        public DateTime? MinDeliveryDateFromParent { get; set; }
    }
}
